package org.demo.loanservice.dto.enumDto;

public enum TransactionCode {
    LOAN_DISBURSEMENT,
    LOAN_PAYMENT,
    PENALTY_NOT_YET_PAID,
    EARLY_PAYMENT_INTEREST,
    LATE_PAYMENT_PENALTY,
    EARLY_REPAYMENT_PENALTY,
    CALCULATE_INTEREST,
    CALCULATE_LATE_PAYMENT_PENALTY,
    CALCULATE_EARLY_REPAYMENT_PENALTY,
}
