package com.example.notification_service.domain.enumValue;

public enum Template {
    LOAN_PAYMENT_SUCCESSFUL,
    OTP_VERIFICATION,
    TRANSACTION_SUCCESS,
    TRANSACTION_SUSPICIOUS,
    CUSTOMER_WELCOME,
    CUSTOMER_REGISTRATION_SUCCESSFUL,
    CUSTOMER_INFORMATION_UPDATE,
    ACCOUNT_LOAN_REGISTER_SUCCESSFUL,
    ACCOUNT_SAVINGS_REGISTER_SUCCESSFUL,
    ACCOUNT_PAYMENT_REGISTER_SUCCESSFUL,
    LOAN_REMIND_DEADLINE,
    LOAN_DISBURSEMENT_SUCCESS,
    LOAN_DISBURSEMENT_FAIL,
    LOAN_FINANCIAL_REVIEW_SUCCESS,
    LOAN_FINANCIAL_REVIEW_FAIL,
    LOAN_COMPLETION,
    LOAN_OVERDUE_DEPT,
    BALANCE_FLUCTUATION,
    TRANSACTION_FAIL,
}
