package com.system.customer_service.util;

import java.io.Serializable;

public class Constant implements Serializable {

    public static final String BLANK = "";
    public static final String CACHE_TRANSACTION_PREFIX = "transaction:";
    public static final String NOT_FOUND = "message.not.found";
    public static final String CREATE_SUCCESS = "message.create.success";
    public static final String CREATE_FAIL = "message.create.fail";
    public static final String UPDATE_SUCCESS = "message.update.success";
    public static final String UPDATE_FAIL = "message.update.fail";
    public static final String DELETE_SUCCESS = "message.delete.success";
    public static final String DELETE_FAIL = "message.delete.fail";
    public static final String UNAUTHORIZED = "message.unauthorized";
    public static final String FORBIDDEN = "message.forbidden";
    public static final String INTERNAL_SERVER_ERROR = "message.internal.server.error";
    public static final String INVALID_PARAMETER = "message.invalid.parameter";
    public static final String INVALID_FORMAT_EMAIL = "message.invalid.format.email";
    public static final String PHONE_REQUIRE = "message.phone.require";
    public static final String EMAIL_REQUIRE = "message.email.require";
    public static final String PHONE_SIZE = "message.phone.size";
    public static final String INVALID_PAGE_NUMBER = "message.invalid.page.number";
    public static final String INVALID_PAGE_SIZE = "message.invalid.page.size";
    public static final String INVALID_PROPERTY = "message.invalid.property";
    public static final String INVALID_ACCOUNT = "message.invalid.account";
    public static final String SERVICE_UNAVAILABLE = "message.service.unavailable";
    public static final String REQUEST_TIMEOUT = "message.request.timeout";
    public static final String BANDWIDTH_LIMIT_EXCEEDED = "message.bandwidth.limit.exceeded";
    public static final String TOO_MANY_REQUESTS = "message.too.many.requests";
    public static final String BANK_NAME_REQUIRE = "message.bank.name.require";
    public static final String BANK_NAME_SIZE = "message.bank.name.size";
    public static final String SHORT_NAME_REQUIRE = "message.short.name.require";
    public static final String SHORT_NAME_SIZE = "message.short.name.size";
    public static final String BANK_CODE_REQUIRE = "message.bank.code.require";
    public static final String BANK_CODE_SIZE = "message.bank.code.size";
    public static final String SWIFT_CODE_REQUIRE = "message.swift.code.require";
    public static final String SWIFT_CODE_SIZE = "message.swift.code.size";
    public static final String NAPAS_CODE_REQUIRE = "message.napas.code.require";
    public static final String NAPAS_CODE_SIZE = "message.napas.code.size";
    public static final String IS_AVAILABLE_REQUIRE = "message.is.available.require";
    public static final String INVALID_EXTERNAL_BANK = "message.invalid.external.bank";
    public static final String INVALID_BANK_CODE = "message.invalid.bank.code";
    public static final String DUPLICATE_BANK_CODE = "message.duplicate.bank.code";
    public static final String INVALID_NAPAS_CODE = "message.invalid.napas.code";
    public static final String DUPLICATE_NAPAS_CODE = "message.duplicate.napas.code";
    public static final String INVALID_SWIFT_CODE = "message.invalid.swift.code";
    public static final String DUPLICATE_SWIFT_CODE = "message.duplicate.swift.code";
    public static final String INVALID_IMAGE_FILE = "message.invalid.image.file";
    public static final String INVALID_IMAGE_FILE_SIZE = "message.invalid.image.file.size";
    public static final String INVALID_IMAGE_FILE_TYPE = "message.invalid.image.file.type";
    public static final String UNSUPPORTED_MEDIA_TYPE = "message.unsupported.media.type";
    public static final String PAYLOAD_TOO_LARGE = "message.payload.too.media";
    public static final String INVALID_OTP_CODE = "message.invalid.otp.code";
    public static final String INSUFFICIENT_BALANCE = "message.insufficient.balance";
    public static final String SEND_OTP_SUCCESS = "message.send.otp.success";
    public static final String SEND_OTP_FAILED = "message.send.otp.failed";
    public static final String USER_ROLE = "USER";
    public static final String ADMIN_ROLE = "ADMIN";
}
